
mode = 38

[0]
1 = ["gamepad", "1", "TOGGLE"]
2 = ["gamepad", "2", "TOGGLE"]
3 = ["gamepad", "3", "TOGGLE"]
4 = ["gamepad", "4", "TOGGLE"]
5 = ["gamepad", "5", "TOGGLE"]
6 = ["gamepad", "6", "TOGGLE"]
7 = ["gamepad", "7", "TOGGLE"]
8 = ["gamepad", "8", "TOGGLE"]
9 = ["gamepad", "9", "TOGGLE"]
10 = ["gamepad", "10", "TOGGLE"]
11 = ["gamepad", "11", "TOGGLE"]
12 = ["gamepad", "12", "TOGGLE"]
13 = ["gamepad", "13", "TOGGLE"]
14 = ["gamepad", "14", "TOGGLE"]
15 = ["gamepad", "15", "TOGGLE"]
16 = ["gamepad", "16", "TOGGLE"]
17 = ["gamepad", "17", "TOGGLE"]
18 = ["gamepad", "18", "TOGGLE"]
19 = ["gamepad", "19", "TOGGLE"]
20 = ["gamepad", "20", "TOGGLE"]
21 = ["gamepad", "21", "TOGGLE"]
22 = ["gamepad", "22", "TOGGLE"]
23 = ["gamepad", "23", "TOGGLE"]
24 = ["gamepad", "24", "TOGGLE"]
25 = ["gamepad", "25", "TOGGLE"]
26 = ["gamepad", "26", "TOGGLE"]
27 = ["gamepad", "27", "TOGGLE"]
28 = ["gamepad", "28", "TOGGLE"]
29 = ["gamepad", "29", "TOGGLE"]
30 = ["gamepad", "30", "TOGGLE"]
31 = ["gamepad", "31", "TOGGLE"]
32 = ["gamepad", "32", "TOGGLE"]
33 = ["gamepad", "33", "TOGGLE"]
34 = ["gamepad", "34", "TOGGLE"]
35 = ["gamepad", "35", "TOGGLE"]
36 = ["gamepad", "36", "TOGGLE"]
37 = ["gamepad", "37", "TOGGLE"]
38 = ["gamepad", "38", "TOGGLE"]

[1]
1 = ["key", "CONTROL", "C"]
2 = ["string", "macro string"]
3 = ["NONE"]
4 = ["NONE"]
5 = ["NONE"]
6 = ["NONE"]
7 = ["NONE"]
8 = ["NONE"]
9 = ["NONE"]
10 = ["NONE"]
11 = ["NONE"]
12 = ["NONE"]
13 = ["NONE"]
14 = ["NONE"]
15 = ["NONE"]
16 = ["NONE"]
17 = ["NONE"]
18 = ["NONE"]
19 = ["NONE"]
20 = ["NONE"]
21 = ["NONE"]
22 = ["NONE"]
23 = ["NONE"]
24 = ["NONE"]
25 = ["NONE"]
26 = ["NONE"]
27 = ["NONE"]
28 = ["NONE"]
29 = ["NONE"]
30 = ["NONE"]
31 = ["NONE"]
32 = ["NONE"]
33 = ["NONE"]
34 = ["NONE"]
35 = ["NONE"]
36 = ["NONE"]
37 = ["NONE"]
38 = ["NONE"]

[2]
1 = ["NONE"]
2 = ["NONE"]
3 = ["NONE"]
4 = ["NONE"]
5 = ["NONE"]
6 = ["NONE"]
7 = ["NONE"]
8 = ["NONE"]
9 = ["NONE"]
10 = ["NONE"]
11 = ["NONE"]
12 = ["NONE"]
13 = ["NONE"]
14 = ["NONE"]
15 = ["NONE"]
16 = ["NONE"]
17 = ["NONE"]
18 = ["NONE"]
19 = ["NONE"]
20 = ["NONE"]
21 = ["NONE"]
22 = ["NONE"]
23 = ["NONE"]
24 = ["NONE"]
25 = ["NONE"]
26 = ["NONE"]
27 = ["NONE"]
28 = ["NONE"]
29 = ["NONE"]
30 = ["NONE"]
31 = ["NONE"]
32 = ["NONE"]
33 = ["NONE"]
34 = ["NONE"]
35 = ["NONE"]
36 = ["NONE"]
37 = ["NONE"]
38 = ["NONE"]