
mode = 38

[0]
1 = ["TOGGLE", "KEY", "CONTROL", "A"]
2 = ["PUSH", "STRING", "macro string"]
3 = ["PUSH", "NONE"]
4 = ["PUSH", "NONE"]
5 = ["PUSH", "NONE"]
6 = ["PUSH", "NONE"]
7 = ["PUSH", "NONE"]
8 = ["PUSH", "NONE"]
9 = ["PUSH", "NONE"]
10 = ["PUSH", "NONE"]
11 = ["PUSH", "NONE"]
12 = ["PUSH", "NONE"]
13 = ["PUSH", "NONE"]
14 = ["PUSH", "NONE"]
15 = ["PUSH", "NONE"]
16 = ["PUSH", "NONE"]
17 = ["PUSH", "NONE"]
18 = ["PUSH", "NONE"]
19 = ["PUSH", "NONE"]
20 = ["PUSH", "NONE"]
21 = ["PUSH", "NONE"]
22 = ["PUSH", "NONE"]
23 = ["PUSH", "NONE"]
24 = ["PUSH", "NONE"]
25 = ["PUSH", "NONE"]
26 = ["PUSH", "NONE"]
27 = ["PUSH", "NONE"]
28 = ["PUSH", "NONE"]
29 = ["PUSH", "NONE"]
30 = ["PUSH", "NONE"]
31 = ["PUSH", "NONE"]
32 = ["PUSH", "NONE"]
33 = ["PUSH", "NONE"]
34 = ["PUSH", "NONE"]
35 = ["PUSH", "NONE"]
36 = ["PUSH", "NONE"]
37 = ["PUSH", "NONE"]
38 = ["PUSH", "NONE"]

[1]
1 = ["PUSH", "GAMEPAD", "1"]
2 = ["PUSH", "GAMEPAD", "2"]
3 = ["PUSH", "GAMEPAD", "3"]
4 = ["PUSH", "GAMEPAD", "4"]
5 = ["PUSH", "GAMEPAD", "5"]
6 = ["PUSH", "GAMEPAD", "6"]
7 = ["PUSH", "GAMEPAD", "7"]
8 = ["PUSH", "GAMEPAD", "8"]
9 = ["PUSH", "GAMEPAD", "9"]
10 = ["PUSH", "GAMEPAD", "10"]
11 = ["PUSH", "GAMEPAD", "11"]
12 = ["PUSH", "GAMEPAD", "12"]
13 = ["PUSH", "GAMEPAD", "13"]
14 = ["PUSH", "GAMEPAD", "14"]
15 = ["PUSH", "GAMEPAD", "15"]
16 = ["PUSH", "GAMEPAD", "16"]
17 = ["PUSH", "GAMEPAD", "17"]
18 = ["PUSH", "GAMEPAD", "18"]
19 = ["PUSH", "GAMEPAD", "19"]
20 = ["PUSH", "GAMEPAD", "20"]
21 = ["PUSH", "GAMEPAD", "21"]
22 = ["PUSH", "GAMEPAD", "22"]
23 = ["PUSH", "GAMEPAD", "23"]
24 = ["PUSH", "GAMEPAD", "24"]
25 = ["PUSH", "GAMEPAD", "25"]
26 = ["PUSH", "GAMEPAD", "26"]
27 = ["PUSH", "GAMEPAD", "27"]
28 = ["PUSH", "GAMEPAD", "28"]
29 = ["PUSH", "GAMEPAD", "29"]
30 = ["PUSH", "GAMEPAD", "30"]
31 = ["PUSH", "GAMEPAD", "31"]
32 = ["PUSH", "GAMEPAD", "32"]
33 = ["PUSH", "GAMEPAD", "33"]
34 = ["PUSH", "GAMEPAD", "34"]
35 = ["PUSH", "GAMEPAD", "35"]
36 = ["PUSH", "GAMEPAD", "36"]
37 = ["PUSH", "GAMEPAD", "37"]
38 = ["PUSH", "GAMEPAD", "38"]

[2]
1 = ["PUSH", "NONE"]
2 = ["PUSH", "NONE"]
3 = ["PUSH", "NONE"]
4 = ["PUSH", "NONE"]
5 = ["PUSH", "NONE"]
6 = ["PUSH", "NONE"]
7 = ["PUSH", "NONE"]
8 = ["PUSH", "NONE"]
9 = ["PUSH", "NONE"]
10 = ["PUSH", "NONE"]
11 = ["PUSH", "NONE"]
12 = ["PUSH", "NONE"]
13 = ["PUSH", "NONE"]
14 = ["PUSH", "NONE"]
15 = ["PUSH", "NONE"]
16 = ["PUSH", "NONE"]
17 = ["PUSH", "NONE"]
18 = ["PUSH", "NONE"]
19 = ["PUSH", "NONE"]
20 = ["PUSH", "NONE"]
21 = ["PUSH", "NONE"]
22 = ["PUSH", "NONE"]
23 = ["PUSH", "NONE"]
24 = ["PUSH", "NONE"]
25 = ["PUSH", "NONE"]
26 = ["PUSH", "NONE"]
27 = ["PUSH", "NONE"]
28 = ["PUSH", "NONE"]
29 = ["PUSH", "NONE"]
30 = ["PUSH", "NONE"]
31 = ["PUSH", "NONE"]
32 = ["PUSH", "NONE"]
33 = ["PUSH", "NONE"]
34 = ["PUSH", "NONE"]
35 = ["PUSH", "NONE"]
36 = ["PUSH", "NONE"]
37 = ["PUSH", "NONE"]
38 = ["PUSH", "NONE"]